#!/usr/bin/bash

build(){
  sudo mvn compile assembly:single $1;
}

rebuild(){
  sudo mvn clean compile assembly:single $1;
}

compile(){
  sudo mvn compile -q;
}

clean(){
  sudo mvn clean;
}

run(){
    Main=$1;
    shift;
    sudo mvn -q exec:java -Dexec.mainClass=$Main $@;
}

case $1 in
  build)
    build $2;
    ;;
  rebuild)
    rebuild $2;
    ;;
  clean)
    clean;
    ;;
  run)
    shift;
    run $@;
    ;;
  compile)
    compile;
    ;;
  *)
    usage_string=$(declare -F | awk '{print $3, "|"}');
    usage_string=${usage_string::-2};
    echo "Usage: {" $usage_string "}";
    echo "run (java main class) - execute java main class";
    ;;
esac

exit 0;
