// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basic_api.proto

package com.usth.hieplnc.api.grpc.basic;

public interface ActionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.usth.hieplnc.api.grpc.basic.ActionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string route = 1;</code>
   */
  java.lang.String getRoute();
  /**
   * <code>string route = 1;</code>
   */
  com.google.protobuf.ByteString
      getRouteBytes();

  /**
   * <code>string jsonAction = 2;</code>
   */
  java.lang.String getJsonAction();
  /**
   * <code>string jsonAction = 2;</code>
   */
  com.google.protobuf.ByteString
      getJsonActionBytes();

  /**
   * <code>string jsonParam = 3;</code>
   */
  java.lang.String getJsonParam();
  /**
   * <code>string jsonParam = 3;</code>
   */
  com.google.protobuf.ByteString
      getJsonParamBytes();
}
