// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basic_api.proto

package com.usth.hieplnc.api.grpc.basic;

/**
 * <pre>
 **
 * List of message definition
 * </pre>
 *
 * Protobuf type {@code com.usth.hieplnc.api.grpc.basic.ActionRequest}
 */
public final class ActionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.usth.hieplnc.api.grpc.basic.ActionRequest)
    ActionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ActionRequest.newBuilder() to construct.
  private ActionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ActionRequest() {
    route_ = "";
    jsonAction_ = "";
    jsonParam_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ActionRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ActionRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            route_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            jsonAction_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            jsonParam_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.usth.hieplnc.api.grpc.basic.BasicApi.internal_static_com_usth_hieplnc_api_grpc_basic_ActionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.usth.hieplnc.api.grpc.basic.BasicApi.internal_static_com_usth_hieplnc_api_grpc_basic_ActionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.usth.hieplnc.api.grpc.basic.ActionRequest.class, com.usth.hieplnc.api.grpc.basic.ActionRequest.Builder.class);
  }

  public static final int ROUTE_FIELD_NUMBER = 1;
  private volatile java.lang.Object route_;
  /**
   * <code>string route = 1;</code>
   * @return The route.
   */
  @java.lang.Override
  public java.lang.String getRoute() {
    java.lang.Object ref = route_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      route_ = s;
      return s;
    }
  }
  /**
   * <code>string route = 1;</code>
   * @return The bytes for route.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRouteBytes() {
    java.lang.Object ref = route_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      route_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JSONACTION_FIELD_NUMBER = 2;
  private volatile java.lang.Object jsonAction_;
  /**
   * <code>string jsonAction = 2;</code>
   * @return The jsonAction.
   */
  @java.lang.Override
  public java.lang.String getJsonAction() {
    java.lang.Object ref = jsonAction_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jsonAction_ = s;
      return s;
    }
  }
  /**
   * <code>string jsonAction = 2;</code>
   * @return The bytes for jsonAction.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJsonActionBytes() {
    java.lang.Object ref = jsonAction_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jsonAction_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JSONPARAM_FIELD_NUMBER = 3;
  private volatile java.lang.Object jsonParam_;
  /**
   * <code>string jsonParam = 3;</code>
   * @return The jsonParam.
   */
  @java.lang.Override
  public java.lang.String getJsonParam() {
    java.lang.Object ref = jsonParam_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      jsonParam_ = s;
      return s;
    }
  }
  /**
   * <code>string jsonParam = 3;</code>
   * @return The bytes for jsonParam.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJsonParamBytes() {
    java.lang.Object ref = jsonParam_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      jsonParam_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getRouteBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, route_);
    }
    if (!getJsonActionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, jsonAction_);
    }
    if (!getJsonParamBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, jsonParam_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getRouteBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, route_);
    }
    if (!getJsonActionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, jsonAction_);
    }
    if (!getJsonParamBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, jsonParam_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.usth.hieplnc.api.grpc.basic.ActionRequest)) {
      return super.equals(obj);
    }
    com.usth.hieplnc.api.grpc.basic.ActionRequest other = (com.usth.hieplnc.api.grpc.basic.ActionRequest) obj;

    if (!getRoute()
        .equals(other.getRoute())) return false;
    if (!getJsonAction()
        .equals(other.getJsonAction())) return false;
    if (!getJsonParam()
        .equals(other.getJsonParam())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ROUTE_FIELD_NUMBER;
    hash = (53 * hash) + getRoute().hashCode();
    hash = (37 * hash) + JSONACTION_FIELD_NUMBER;
    hash = (53 * hash) + getJsonAction().hashCode();
    hash = (37 * hash) + JSONPARAM_FIELD_NUMBER;
    hash = (53 * hash) + getJsonParam().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.usth.hieplnc.api.grpc.basic.ActionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.usth.hieplnc.api.grpc.basic.ActionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.usth.hieplnc.api.grpc.basic.ActionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.usth.hieplnc.api.grpc.basic.ActionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.usth.hieplnc.api.grpc.basic.ActionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.usth.hieplnc.api.grpc.basic.ActionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.usth.hieplnc.api.grpc.basic.ActionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.usth.hieplnc.api.grpc.basic.ActionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.usth.hieplnc.api.grpc.basic.ActionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.usth.hieplnc.api.grpc.basic.ActionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.usth.hieplnc.api.grpc.basic.ActionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.usth.hieplnc.api.grpc.basic.ActionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.usth.hieplnc.api.grpc.basic.ActionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * List of message definition
   * </pre>
   *
   * Protobuf type {@code com.usth.hieplnc.api.grpc.basic.ActionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.usth.hieplnc.api.grpc.basic.ActionRequest)
      com.usth.hieplnc.api.grpc.basic.ActionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.usth.hieplnc.api.grpc.basic.BasicApi.internal_static_com_usth_hieplnc_api_grpc_basic_ActionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.usth.hieplnc.api.grpc.basic.BasicApi.internal_static_com_usth_hieplnc_api_grpc_basic_ActionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.usth.hieplnc.api.grpc.basic.ActionRequest.class, com.usth.hieplnc.api.grpc.basic.ActionRequest.Builder.class);
    }

    // Construct using com.usth.hieplnc.api.grpc.basic.ActionRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      route_ = "";

      jsonAction_ = "";

      jsonParam_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.usth.hieplnc.api.grpc.basic.BasicApi.internal_static_com_usth_hieplnc_api_grpc_basic_ActionRequest_descriptor;
    }

    @java.lang.Override
    public com.usth.hieplnc.api.grpc.basic.ActionRequest getDefaultInstanceForType() {
      return com.usth.hieplnc.api.grpc.basic.ActionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.usth.hieplnc.api.grpc.basic.ActionRequest build() {
      com.usth.hieplnc.api.grpc.basic.ActionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.usth.hieplnc.api.grpc.basic.ActionRequest buildPartial() {
      com.usth.hieplnc.api.grpc.basic.ActionRequest result = new com.usth.hieplnc.api.grpc.basic.ActionRequest(this);
      result.route_ = route_;
      result.jsonAction_ = jsonAction_;
      result.jsonParam_ = jsonParam_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.usth.hieplnc.api.grpc.basic.ActionRequest) {
        return mergeFrom((com.usth.hieplnc.api.grpc.basic.ActionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.usth.hieplnc.api.grpc.basic.ActionRequest other) {
      if (other == com.usth.hieplnc.api.grpc.basic.ActionRequest.getDefaultInstance()) return this;
      if (!other.getRoute().isEmpty()) {
        route_ = other.route_;
        onChanged();
      }
      if (!other.getJsonAction().isEmpty()) {
        jsonAction_ = other.jsonAction_;
        onChanged();
      }
      if (!other.getJsonParam().isEmpty()) {
        jsonParam_ = other.jsonParam_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.usth.hieplnc.api.grpc.basic.ActionRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.usth.hieplnc.api.grpc.basic.ActionRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object route_ = "";
    /**
     * <code>string route = 1;</code>
     * @return The route.
     */
    public java.lang.String getRoute() {
      java.lang.Object ref = route_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        route_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string route = 1;</code>
     * @return The bytes for route.
     */
    public com.google.protobuf.ByteString
        getRouteBytes() {
      java.lang.Object ref = route_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        route_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string route = 1;</code>
     * @param value The route to set.
     * @return This builder for chaining.
     */
    public Builder setRoute(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      route_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string route = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoute() {
      
      route_ = getDefaultInstance().getRoute();
      onChanged();
      return this;
    }
    /**
     * <code>string route = 1;</code>
     * @param value The bytes for route to set.
     * @return This builder for chaining.
     */
    public Builder setRouteBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      route_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object jsonAction_ = "";
    /**
     * <code>string jsonAction = 2;</code>
     * @return The jsonAction.
     */
    public java.lang.String getJsonAction() {
      java.lang.Object ref = jsonAction_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jsonAction_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string jsonAction = 2;</code>
     * @return The bytes for jsonAction.
     */
    public com.google.protobuf.ByteString
        getJsonActionBytes() {
      java.lang.Object ref = jsonAction_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jsonAction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string jsonAction = 2;</code>
     * @param value The jsonAction to set.
     * @return This builder for chaining.
     */
    public Builder setJsonAction(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      jsonAction_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string jsonAction = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearJsonAction() {
      
      jsonAction_ = getDefaultInstance().getJsonAction();
      onChanged();
      return this;
    }
    /**
     * <code>string jsonAction = 2;</code>
     * @param value The bytes for jsonAction to set.
     * @return This builder for chaining.
     */
    public Builder setJsonActionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      jsonAction_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object jsonParam_ = "";
    /**
     * <code>string jsonParam = 3;</code>
     * @return The jsonParam.
     */
    public java.lang.String getJsonParam() {
      java.lang.Object ref = jsonParam_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jsonParam_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string jsonParam = 3;</code>
     * @return The bytes for jsonParam.
     */
    public com.google.protobuf.ByteString
        getJsonParamBytes() {
      java.lang.Object ref = jsonParam_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jsonParam_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string jsonParam = 3;</code>
     * @param value The jsonParam to set.
     * @return This builder for chaining.
     */
    public Builder setJsonParam(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      jsonParam_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string jsonParam = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearJsonParam() {
      
      jsonParam_ = getDefaultInstance().getJsonParam();
      onChanged();
      return this;
    }
    /**
     * <code>string jsonParam = 3;</code>
     * @param value The bytes for jsonParam to set.
     * @return This builder for chaining.
     */
    public Builder setJsonParamBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      jsonParam_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.usth.hieplnc.api.grpc.basic.ActionRequest)
  }

  // @@protoc_insertion_point(class_scope:com.usth.hieplnc.api.grpc.basic.ActionRequest)
  private static final com.usth.hieplnc.api.grpc.basic.ActionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.usth.hieplnc.api.grpc.basic.ActionRequest();
  }

  public static com.usth.hieplnc.api.grpc.basic.ActionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ActionRequest>
      PARSER = new com.google.protobuf.AbstractParser<ActionRequest>() {
    @java.lang.Override
    public ActionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ActionRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ActionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ActionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.usth.hieplnc.api.grpc.basic.ActionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

