// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basic_api.proto

package com.usth.hieplnc.api.grpc.basic;

public interface ChunkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.usth.hieplnc.api.grpc.basic.Chunk)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes data = 1;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
