// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basic_api.proto

package com.usth.hieplnc.api.grpc.basic;

public interface StatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.usth.hieplnc.api.grpc.basic.StatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string system = 1;</code>
   */
  java.lang.String getSystem();
  /**
   * <code>string system = 1;</code>
   */
  com.google.protobuf.ByteString
      getSystemBytes();

  /**
   * <code>string action = 2;</code>
   */
  java.lang.String getAction();
  /**
   * <code>string action = 2;</code>
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <code>string result = 3;</code>
   */
  java.lang.String getResult();
  /**
   * <code>string result = 3;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
